04 auth
linluxx/nodejs-hw-rest-api pull request #3
Opened 2023-01-22 13:39 UTC by linluxx

4 дз, перевірте будь-ласка  )

2023-01-22 17:00 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-22 17:00 UTC, KhYulian commented on app.js
> +});
app.use((error, req, res, next) => {
  if (error.name === "ValidationError") {
    return res.status(400).json({ message: error.message });
  }
}); обовязково має бути останньою middleware

2023-01-22 17:00 UTC, KhYulian commented on app.js
> +});
також потрібно додати дефолтний респонс після іфу

2023-01-22 17:00 UTC, KhYulian commented on controllers/user.controller.js
> +  }
Це перевіряє ваша auth middleware

2023-01-22 17:00 UTC, KhYulian commented on controllers/user.controller.js
> +  }
if (!userForLogout) {
    res.status(401).json({
      message: "Not authorized",
    });
  } можна видалити

2023-01-22 19:07 UTC, linluxx commented on controllers/user.controller.js
> +  }
Зробила

2023-01-22 19:11 UTC, linluxx commented on app.js
> +});
Зробила

2023-01-23 07:42 UTC, KhYulian approved these changes
Чудова робота :)

2023-01-23 07:42 UTC, merged